// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using test_2_ASP_Dbcontext_Web_API.Data;

#nullable disable

namespace test_2_ASP_Dbcontext_Web_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("test_2_ASP_Dbcontext.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rate")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "First Author",
                            DateAdded = new DateTime(2025, 4, 23, 14, 19, 18, 719, DateTimeKind.Local).AddTicks(2173),
                            Description = "1st book description",
                            Genre = "Biography",
                            Rate = 5,
                            Title = "1st book title"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Second Author",
                            DateAdded = new DateTime(2025, 4, 23, 14, 19, 18, 721, DateTimeKind.Local).AddTicks(2200),
                            Description = "2nd book description",
                            Genre = "Biography",
                            Rate = 4,
                            Title = "2nd book title"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
