-- area
/* area
INSERT INTO `shopee`.`area` (`name_area`) VALUES ('Nước ngoài');
INSERT INTO `shopee`.`area` (`name_area`) VALUES ('Đài Loan');
INSERT INTO `shopee`.`area` (`name_area`) VALUES ('Hong Kong');
INSERT INTO `shopee`.`area` (`name_area`) VALUES ('Singapore');
INSERT INTO `shopee`.`area` (`name_area`) VALUES ('Indonesia');
INSERT INTO `shopee`.`area` (`name_area`) VALUES ('Malaysia');
INSERT INTO `shopee`.`area` (`name_area`) VALUES ('Việt Nam');
INSERT INTO `shopee`.`area` (`name_area`) VALUES ('Thái Lan');
INSERT INTO `shopee`.`area` (`name_area`) VALUES ('Philippines');
INSERT INTO `shopee`.`area` (`name_area`) VALUES ('Hàn Quốc');
INSERT INTO `shopee`.`area` (`name_area`) VALUES ('japan');
INSERT INTO `shopee`.`area` (`name_area`) VALUES ('Brazil');
INSERT INTO `shopee`.`area` (`name_area`) VALUES ('Mexico');
INSERT INTO `shopee`.`area` (`name_area`) VALUES ('Ba Lan');
INSERT INTO `shopee`.`area` (`name_area`) VALUES ('Colombia');
INSERT INTO `shopee`.`area` (`name_area`) VALUES ('Chile');
INSERT INTO `shopee`.`area` (`name_area`) VALUES ('Argentina');
*/

-- main_account
/* main_account
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('thanh12345', 'Pass12345', '7', '0935333566', 'thanhdanang2@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('quyennguyenshop', 'Pass12345', '5', '0935789633', 'quyennvhde170370@fpt.edu.vn');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('hanshopdee', 'Pass12345', '4', '0905997224', 'hanshop@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('thangnnd874', 'Pass12345', '1', '0811004007', 'thangdept@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('thangudhjs', 'Pass12345', '3', '0931130366', 'john.doe123@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('bluesky89', 'Pass12345', '2', '0931672898', 'jane.smith456@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('reddragon23', 'Pass12345', '2', '0934830617', 'michael.brown789@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('silverfox77', 'Pass12345', '3', '0934377783', 'sarah.jones321@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('greenleaf56', 'Pass12345', '7', '0939520379', 'david.johnson654@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('stargazer44', 'Pass12345', '10', '0932709542', 'emily.davis987@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('darkknight12', 'Pass12345', '1', '0936847988', 'chris.wilson111@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('mysticmoon9', 'Pass12345', '2', '0938474336', 'anna.moore222@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('wildwolf21', 'Pass12345', '3', '0932875871', 'brian.taylor333@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('oceanwave33', 'Pass12345', '4', '0934493282', 'laura.anderson444@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('goldensun55', 'Pass12345', '5', '0935871234', 'kevin.thomas555@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('cosmicstar67', 'Pass12345', '6', '0931234567', 'olivia.jackson666@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('blazingfire88', 'Pass12345', '7', '0932345678', 'robert.white777@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('silentshadow14', 'Pass12345', '8', '0903456789', 'sophia.harris888@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('neonninja22', 'Pass12345', '9', '0904567890', 'james.martin999@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('crystalclear78', 'Pass12345', '10', '0905678901', 'mia.lee101@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('thunderbolt66', 'Pass12345', '11', '0906789012', 'william.walker202@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('midnightowl45', 'Pass12345', '12', '0907890123', 'ava.young303@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('solarflare32', 'Pass12345', '13', '0908901234', 'alexander.king404@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('echospirit11', 'Pass12345', '14', '0909012345', 'isabella.scott505@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('blazingtrail99', 'Pass12345', '15', '0900123456', 'john.doe9821@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('phantomrider20', 'Pass12345', '16', '0901230987', 'robert.white888@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('shiningarmor31', 'Pass12345', '17', '0902341098', 'sophia.harris@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('silverstone53', 'Pass12345', '7', '0903452109', 'isabella.scott@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('fakeshopee', 'T123456789', '7', '0935430002', 'tienngqueson@gmail.com');
INSERT INTO `shopee`.`main_account` (`business_ID`, `password`, `account_area`, `phone_number`, `email`) VALUES ('tien729467', 'T123456789', '7', '0876811003', 'tientpnde170390@fpt.edu.vn');
*/

-- shop
/* shop
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0931234567', 'Pass12345', 'aaron.jones32@gmail.com', 'Mộc Mạc Store', '1');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0902345678', 'Pass12345', 'bella.smith87@gmail.com', 'BlueSky Shop', '2');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0873456789', 'Pass12345', 'carter.brown56@gmail.com\n', 'Thế Giới Đồ Gia Dụng', '3');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0934567890', 'Pass12345', 'diana.evans34@gmail.com\n', 'Fashionista Corner', '4');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0905678901', 'Pass12345', 'emma.james91@gmail.com\n', 'MyHome Essentials\n', '5');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0876789012', 'Pass12345', 'frank.white12@gmail.com\n', 'Sắc Màu Thời Trang\n', '6');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0937890123', 'Pass12345', 'grace.thomas89@gmail.com\n', 'TechnoHub\n', '11');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0908901234', 'Pass12345', 'henry.clark45@gmail.com\n', 'Kids Paradise\n', '12');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0879012345', 'Pass12345', 'isabella.lewis77@gmail.com\n', 'Urban Outfitters\n', '13');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0930123456', 'Pass12345', 'jack.wright63@gmail.com\n', 'Vintage Treasures\n', '14');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0901230987', 'Pass12345', 'katie.robinson23@gmail.com\n', 'Sports Central\n', '15');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0872341098', 'Pass12345', 'liam.king58@gmail.com\n', 'GreenLife Organics\n', '16');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0933452109', 'Pass12345', 'mia.harris72@gmail.com\n', 'Beauty Bliss\n', '21');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0904563210', 'Pass12345', 'nathan.walker91@gmail.com\n', 'Trendy Footwear\n', '22');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0875674321', 'Pass12345', 'olivia.hall29@gmail.com\n', 'Elegant Accessories\n', '23');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0936785432', 'Pass12345', 'paul.allen67@gmail.com\n', 'Happy Kids Store\n', '24');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0907896543', 'Pass12345', 'quincy.young84@gmail.com\n', 'Cozy Home Decor\n', '25');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0878907654', 'Pass12345', 'rachel.hernandez30@gmail.com\n', 'Luxe Watches\n', '26');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0939018765', 'Pass12345', 'samuel.lopez48@gmail.com\n', 'EcoLiving Shop\n', '30');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0900129876', 'Pass12345', 'tina.martin99@gmail.com\n', 'Book Haven\n', '1');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0871234567', 'Pass12345', 'ursula.green27@gmail.com\n', 'Chic Boutique\n', '1');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0932345678', 'Pass12345', 'victor.adams53@gmail.com\n', 'Gadget World\n', '2');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0903456789', 'Pass12345', 'william.johnson19@gmail.com\n', 'Artistic Creations\n', '3');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0874567890', 'Pass12345', 'xavier.taylor42@gmail.com\n', 'Wellness Wonders\n', '4');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0935678901', 'Pass12345', 'yvonne.morris65@gmail.com\n', 'Fresh  Natural\n', '5');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0906789012', 'Pass12345', 'zachary.moore74@gmail.com\n', 'Modern Office\n', '6');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0877890123', 'Pass12345', 'amelia.carter38@gmail.com\n', 'Glamour Glitz\n', '11');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0938901234', 'Pass12345', 'charlotte.davis84@gmail.com\n', 'Culinary Delights\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0909012345', 'Pass12345', 'benjamin.hughes21@gmail.com\n', 'Zen Garden Supplies\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0870123456', 'Pass12345', 'daniel.lee56@gmail.com\n', 'Cozy Knitwear\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0321234567', 'Pass12345', 'eleanor.scott93@gmail.com\n', 'Outdoor Adventures\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0332345678', 'Pass12345', 'finn.evans60@gmail.com\n', 'Simply Stylish\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0343456789', 'Pass12345', 'gabriella.young12@gmail.com\n', 'Pet Paradise\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0814567890', 'Pass12345', 'harry.harris48@gmail.com\n', 'DIY Haven\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0825678901', 'Pass12345', 'isabelle.wood37@gmail.com\n', 'Blissful Bedding\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0836789012', 'Pass12345', 'jackson.baker71@gmail.com\n', 'Tech Trends\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0707890123', 'Pass12345', 'kevin.anderson49@gmail.com\n', 'Little Treasures\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0768901234', 'Pass12345', 'lily.bell28@gmail.com\n', 'Gourmet Treats\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0789012345', 'Pass12345', 'max.turner91@gmail.com\n', 'Crafty Corner\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0320123456', 'Pass12345', 'nora.wright45@gmail.com\n', 'Urban Chic\n', '29');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0331230987', 'Pass12345', 'owen.clark76@gmail.com\n', 'Garden Goodies\n', '29');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0935430002', 'T123456789', 'tienngqueson@gmail.com', 'Tiến thanh', '29');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0813452109', 'Pass12345', 'quinn.bennett62@gmail.com\n', 'Adventure Gear\n', '29');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0824563210', 'Pass12345', 'ruby.campbell81@gmail.com\n', 'Luxe Living\n', '1');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0876811003', 'T123456789', 'tientpnde170390@fpt.edu.vn', 'Vua lì đòn', '30');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0706785432', 'Pass12345', 'theo.hall59@gmail.com\n', 'Sweet Treats\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0767896543', 'Pass12345', 'uma.jones24@gmail.com\n', 'Cozy Corner\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0788907654', 'Pass12345', 'vincent.king35@gmail.com\n', 'Sparkle Shine\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0876811022', 'T123456789', 'wendy.smith83@gmail.com\n', 'Gadget Geeks\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0330129876', 'Pass12345', 'xander.lewis98@gmail.com\n', 'Pure Elegance\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0341234567', 'Pass12345', 'yara.morris66@gmail.com\n', 'Fit Fab\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0935430003', 'T123456789', 'zane.taylor12@gmail.com\n', 'Stylish Threads\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0823456789', 'Pass12345', 'abigail.carter43@gmail.com\n', 'Little Wonders\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0834567890', 'Pass12345', 'bradley.hughes87@gmail.com\n', 'Gourmet Pantry\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0705678901', 'Pass12345', 'chloe.davis78@gmail.com\n', 'Travel Essentials\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`) VALUES ('0766789012', 'Pass12345', 'declan.lee29@gmail.com\n', 'Beauty Beyond\n');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0787890123', 'Pass12345', 'emily.scott64@gmail.com\n', 'Modern Living\n', '21');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0328901234', 'Pass12345', 'freddie.evans35@gmail.com\n', 'Trendy Tech\n', '22');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0339012345', 'Pass12345', 'grace.young88@gmail.com\n', 'Home Comforts\n', '23');
INSERT INTO `shopee`.`shop` (`phone_number`, `password`, `email`, `shop_name`, `id_main_account`) VALUES ('0340123456', 'Pass12345', 'harper.bell90@gmail.com\n', 'Luxe Decor\n', '24');
*/

-- form_of_identification
/* form_of_identification
INSERT INTO `shopee`.`form_of_identification` (`name_form`) VALUES ('Căn cước công dân');
INSERT INTO `shopee`.`form_of_identification` (`name_form`) VALUES ('Chứng minh nhân dân');
INSERT INTO `shopee`.`form_of_identification` (`name_form`) VALUES ('Hộ chiếu');
*/

-- shipping_method
/* shipping_method
INSERT INTO `shopee`.`shipping_method` (`method_name`) VALUES ('Hoả Tốc');
INSERT INTO `shopee`.`shipping_method` (`method_name`) VALUES ('Nhanh');
INSERT INTO `shopee`.`shipping_method` (`method_name`) VALUES ('Tiết Kiệm');
INSERT INTO `shopee`.`shipping_method` (`method_name`) VALUES ('Hàng Cồng Kềnh');
*/

-- payment_method
/* payment_method
INSERT INTO `shopee`.`payment_method` (`payment_method_name`) VALUES ('Chuyển khoản');
INSERT INTO `shopee`.`payment_method` (`payment_method_name`) VALUES ('Ví Shopee Pay');
INSERT INTO `shopee`.`payment_method` (`payment_method_name`) VALUES ('ví Shopee Trả Sau');
INSERT INTO `shopee`.`payment_method` (`payment_method_name`) VALUES ('Thanh Toán Khi Nhận Hàng');
*/

-- category
INSERT INTO `shopee`.`category` (`name_category`) VALUES ('Thời Trang Nữ');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo', '1');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo hai dây và ba lỗ', '2');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo ống', '2');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo thun', '2');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo sơ mi', '2');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo polo', '2');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo liền thân', '2');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('khác', '2');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quần', '1');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quần legging', '10');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quần dài', '10');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '10');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quần đùi', '1');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quần đùi', '14');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quần váy', '14');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '14');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Váy', '1');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quần Jeans', '1');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đầm', '1');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Váy cưới', '1');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ liền thân', '1');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ bay ( Jumpsuits )', '22');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ bay ngắn ( Playsuits )', '22');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quần yếm', '22');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '22');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo khoác', '1');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo khoác mùa đông', '27');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo choàng', '27');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo blazer', '27');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo khoác ngoài', '27');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo vest', '27');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '27');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo len', '1');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Hoodie và Áo nỉ', '1');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo khoác nỉ', '35');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo hoodies', '35');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('khác', '35');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bộ', '1');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bộ đồ đôi', '39');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bộ đồ gia đình', '39');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ lẻ', '39');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '39');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ lót', '1');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bộ đồ lót', '44');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo ngực', '44');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quần lót', '44');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ lót giữ nhiệt', '44');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Phụ kiện đồ lót', '44');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ định hình', '44');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ lót bảo hộ', '44');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ lót gợi cảm', '44');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '44');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dây áo lót', '49');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Miếng mút rời', '49');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Miếng dán ngực', '49');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '49');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ ngủ', '1');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Pyjama', '58');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Váy ngủ', '58');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo choàng ngủ, Áo khoác kim ...', '58');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '58');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ Bầu', '1');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo ngực cho con bú', '63');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đầm Bầu', '63');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo bầu', '63');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ mặc cho con bú', '63');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bộ đồ bầu', '63');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quần Bầu, Váy bầu', '63');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '63');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ truyền thống', '1');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo', '71');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quần và chân váy', '71');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bộ', '71');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đầm', '71');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '71');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ hoá trang', '1');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '1');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Vải', '1');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Vải cotton', '79');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Vải len', '79');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Vải nhung, lụa, satin', '79');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Vải da', '79');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Vải nylon', '79');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Vải denim', '79');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Vải canvas', '79');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '79');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Vớ / Tất', '1');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Tất', '88');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quần tất', '88');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '88');
INSERT INTO `shopee`.`category` (`name_category`) VALUES ('Thời Trang Nam');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quần Jean', '92');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Hoodie & Áo nỉ', '92');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo Hoodie', '94');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ảo nỉ', '94');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '94');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo len', '92');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo khoác', '92');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo khoác mùa đông & Áo choàng', '99');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo khoác', '99');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo khoác vest', '99');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '99');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Com lê', '92');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bộ Com Lê', '104');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo khoác & Blazer', '104');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quần âu', '104');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo vest & Gi lê', '104');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '104');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quần dài', '92');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quần túi hộp', '110');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quần jogger', '110');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quần dài', '110');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '110');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quần đùi', '92');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo', '92');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo sơ mi', '116');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo polo', '116');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo thun', '116');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo ba lỗ', '116');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '116');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ lót', '92');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quần lót', '122');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo lót', '122');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ lót giữ nhiệt', '122');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '122');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ ngủ', '92');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bộ', '92');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Trang phục truyền thống', '92');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo', '129');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quần', '129');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bộ', '129');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '129');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ hoá trang', '92');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Trang phục ngành nghề', '92');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '92');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Vớ / Tất', '92');
INSERT INTO `shopee`.`category` (`name_category`) VALUES ('Sắc Đẹp');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Chăm sóc tay, chân & móng', '138');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Chăm sóc tóc', '138');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Chăm sóc nam giới', '138');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Nước Hoa', '138');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Trang điểm', '138');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dụng cụ làm đẹp', '138');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Chăm sóc da mặt', '138');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bộ sản phẩm làm đẹp', '138');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '138');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Tắm & Chăm sóc cơ thể', '138');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Chăm sóc tay', '139');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Chăm sóc chân', '139');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Chăm sóc móng', '139');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '139');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Mặt nạ cho tay', '149');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Kem dưỡng, dầu dưỡng & sữa dưỡng', '149');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Xà phòng rửa tay', '149');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '149');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khử mùi hôi chân', '150');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Mặt nạ cho chân', '150');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Kem dưỡng, dầu dưỡng & sữa dưỡng', '150');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '150');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Sơn nền & Sơn bóng', '151');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Sơn móng', '151');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dụng cụ tẩy sơn móng', '151');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dưỡng móng', '151');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Móng giả', '151');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Hình dán móng', '151');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dụng cụ & thiết bị làm móng', '151');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '151');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Nali Gel', '151');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dầu gội', '140');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thuốc nhuộm tóc', '140');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Sản phẩm dưỡng tóc', '140');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dầu xả', '140');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Sản phẩm tạo kiểu tóc', '140');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '140');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Sửa tắm & chăm sóc cơ thể', '141');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Chăm sóc da', '141');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Sản phẩm cạo râu & hớt tóc', '141');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Chăm sóc tóc', '141');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '141');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Sữa rửa mặt', '177');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Kem dưỡng ẩm & dưỡng da', '177');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '177');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dưỡng da sau cạo râu', '178');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Kem dưỡng, kem tạo bọt & gel', '178');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dao cạo râu', '178');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy cạo râu', '178');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Cọ cạo râu', '178');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy cạo râu đa chức năng', '178');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Phụ kiện hỗ trợ cạo râu', '178');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '178');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '143');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Trang điểm mặt', '143');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Trang điểm mắt', '143');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Trang điểm môi', '143');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Tẩy trang', '143');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Kem lót', '193');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Kem nền', '193');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Kem BB & CC', '193');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Phấn phủ', '193');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Che khuyết điểm', '193');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Tạo khối & bắt sáng', '193');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Xịt giữ makeup', '193');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Má hồng', '193');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '193');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Phấn mắt', '194');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Kem lót mắt', '194');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bút kẻ mắt', '194');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Mascara', '194');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Kẻ mày', '194');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '194');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Son môi', '195');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Son bóng', '195');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Viền môi', '195');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Son tint', '195');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Son làm căng môi', '195');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '195');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dụng cụ trang điểm', '144');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dụng cụ chăm sóc da mặt', '144');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dụng cụ làm thon gọn cơ thể', '144');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dụng cụ tẩy lông', '144');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dụng cụ chăm sóc tóc', '144');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '144');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('224', 'Khác', '218');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('225', 'Bông tẩy trang', '218');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('226', 'Túi đựng đồ trang điểm', '218');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('227', 'Gương', '218');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('228', 'Dung dịch làm sạch cọ trang điểm', '218');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('229', 'Cọ trang điểm', '218');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('230', 'Bông mút trang điểm', '218');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('231', 'Kẹp bấm mi', '218');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('232', 'Khuôn kẻ chân mày', '218');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('233', 'Mi giả Miếng dán mi & keo dán mí', '218');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('234', 'Chuốt chì kẻ mày', '218');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('235', 'Máy xông mặt', '219');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('236', 'Dụng cụ làm thon gọn & mát xa mặt', '219');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('237', 'Dụng cụ rửa mặt', '219');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('238', 'Khác', '219');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('239', 'Lược chải', '222');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('240', 'Máy sấy tóc', '222');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('241', 'Máy tạo kiểu tóc', '222');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('242', 'Dụng cụ tạo kiểu Không nhiệt', '222');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('243', 'Khác', '222');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('244', 'Sữa rửa mặt', '145');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('245', 'Nước cân bằng da', '145');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('246', 'Kem dưỡng ẩm', '145');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('247', 'Dầu dưỡng ẩm', '145');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('248', 'Xịt khoáng', '145');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('249', 'Tinh chất dưỡng', '145');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('250', 'Tẩy tế bào chết', '145');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('251', 'Mặt nạ', '145');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('252', 'Sản phẩm dưỡng mắt', '145');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('253', 'Sản phẩm dưỡng môi', '145');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('254', 'kem chống nắng cho mặt', '145');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('255', 'Kem dưỡng sau chống nắng', '145');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('256', 'Giấy thấm dầu', '145');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('257', 'Sản phẩm trị mụn', '145');
INSERT INTO `shopee`.`category` (`id_category`, `name_category`, `id_parent`) VALUES ('258', 'Khác', '145');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Xà phòng & sữa tắm', '148');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Tẩy tế bào chết cơ thể', '148');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Mặt nạ ủ cơ thể', '148');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dầu dưỡng da', '148');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Kem & sữa dưỡng thể', '148');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khử mùi cơ thể', '148');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dầu massage', '148');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Kem tẩy lông & was lông', '148');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Chống nắng', '148');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Chăm sóc ngực', '148');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '148');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Chống nắng & chăm sóc sau đi nắng', '267');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thuốc nhuộm da', '267');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '267');
INSERT INTO `shopee`.`category` (`name_category`) VALUES ('Sức khoẻ');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thực phẩm chức năng', '273');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '273');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Vật tư y tế', '273');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Chăm sóc cá nhân', '273');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Hỗ trợ tình dục', '273');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Hỗ trợ kiểm soát cân nặng', '274');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Hỗ trợ làm đẹp', '274');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Hỗ trợ tăng cơ', '274');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Hỗ trợ sức khoẻ', '274');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '274');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Kiểm tra và theo dõi sức khỏe', '276');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Cân sức khỏe và phân tích cơ thể', '276');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Chăm sóc mũi', '276');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dụng cụ sơ cứu', '276');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ống nghe y tế', '276');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Sản phẩm giảm đau dùng ngoài da', '276');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dụng cụ thí nghiệm', '276');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bao tay và khẩu trang y tế', '276');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Hỗ trợ chấn thương và khuyết tật', '276');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '276');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy đo huyết áp', '284');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy đo lượng đường trong máu', '284');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy đo nồng độ oxy trong máu', '284');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Nhiệt kế', '284');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '284');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Băng gạc y tế', '287');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Phụ kiện sơ cấp cứu', '287');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Kem và thuốc mỡ', '287');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thuốc sát trùng & khử trùng y tế', '287');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '287');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Nạng chống', '292');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Xe lăn', '292');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dụng cụ nẹp và hỗ trợ khớp', '292');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Trợ thính', '292');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '292');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dung dịch sát khuẩn tay', '277');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Chăm sóc mắt', '277');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Chăm sóc tai', '277');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Vệ sinh răng miệng', '277');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Tã người lớn', '277');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Chăm sóc phụ nữ', '277');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dụng cụ massage và trị liệu', '277');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Chống muỗi & xua đuổi côn trùng', '277');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '277');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Kính áp tròng', '310');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thuốc nhỏ mắt và ngâm áp tròng', '310');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '310');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bàn chải đánh răng', '312');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bàn chải điện & phụ kiện', '312');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Kem đánh răng', '312');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Chỉ nha khoa', '312');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Nước súc miệng', '312');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Răng giả và phụ kiện', '312');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Hỗ trợ trắng răng', '312');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dụng cụ hỗ trợ chỉnh nha', '312');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '312');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Băng vệ sinh có cánh & không cánh', '314');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Tampon', '314');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Que thử thai', '314');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Cốc nguyệt san', '314');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dung dịch vệ sinh phụ nữ', '314');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Kem dưỡng vùng kín', '314');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '314');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bao cao su', '278');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bôi trơn', '278');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Tăng cường sinh lý', '278');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '278');
INSERT INTO `shopee`.`category` (`name_category`) VALUES ('Phụ kiện thời trang');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Nhẫn', '341');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bông tai', '341');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khăn choàng', '341');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Găng tay', '341');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Phụ kiện tóc', '341');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Vòng tay & Lắc tay', '341');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Lắc chân', '341');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Mũ', '341');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dây chuyền', '341');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Kính mắt', '341');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Kim loại quý', '341');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thắt lưng', '341');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Cà vạt & Nơ cổ', '341');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Phụ kiện thêm', '341');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bộ phụ kiện', '341');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '341');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Băng đô tóc', '346');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ buộc tóc & nơ', '346');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Kẹp tóc', '346');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Tóc giả & Tóc nối', '346');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Cài tóc, vương miệng cài tóc', '346');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '346');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Kính mát', '351');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Gọng kính', '351');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Hộp kính và phụ kiện', '351');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '351');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bạc', '352');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Trâm & Ghim cài tóc', '355');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Miếng vá áo', '355');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Mặt dây chuyền và Charm', '355');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Măng sét nam', '355');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Hình xăm dán', '355');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khẩu trang thời trang', '355');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khăn tay', '355');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '355');
INSERT INTO `shopee`.`category` (`name_category`) VALUES ('Thiết Bị Điện Gia Dụng');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy chiếu & phụ kiện', '377');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thiết bị điện gia dụng nhỏ', '377');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thiết bị điện gia dụng lớn', '377');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Tivi & phụ kiện', '377');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ gia dụng nhà bếp', '377');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Mạch điện & Phụ tùng', '377');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Pin', '377');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thiết bị điều khiển từ xa', '377');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '377');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy chiếu & Màn hình chiếu', '378');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bút trình chiếu', '378');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '378');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thiết bị vệ sinh chân & Thư giãn', '379');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy tăm nước', '379');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy may & Phụ kiện', '379');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Điện thoại', '379');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bàn là khô & hơi nước', '379');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thiết bị xử lý không khí', '379');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy hút bụi & Thiết bị làm sạch sàn', '379');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '379');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Điện thoại có dây', '393');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Điện thoại không dây', '393');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy fax', '393');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '393');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy lọc không khí', '395');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy hút ẩm', '395');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '395');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy giặt & Máy sấy', '380');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy nước nóng', '380');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thiết bị làm mát', '380');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thiết bị sấy khô nệm & giày', '380');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy sưởi', '380');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '380');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy giặt', '405');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy sấy quần áo', '405');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '405');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Điều hoà', '407');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy làm mát không khí & Điều hoà cầm tay', '407');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quạt', '407');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '407');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Tivi', '381');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ăng ten Tivi', '381');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Tivi box & Đầu thu kỹ thuật số', '381');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Giá treo tivi', '381');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '381');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy lọc nước', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ấm đun siêu tốc', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Tủ ủ rượu', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy ép, Xay sinh tố & Máy làm sữa đậu nành', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy pha cà phê & phụ kiện', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy trộn thực phẩm', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy rửa bát đĩa', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Lò sưởi, Bếp từ & Bộ điều chỉnh gas', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Nồi chiên không dầu', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Nồi chiên ngập dầu', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Lò vi sóng', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Lò nướng', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy nướng bánh', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy chế biến thực phẩm & Xay thịt', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Nồi nấu đa năng', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Nồi áp suất', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Nồi nấu chậm & Dụng cụ nấu chân không', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Nồi cơm điện', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dụng cụ nấu đặc biệt', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Tủ lạnh', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Tủ đông', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy hút khói', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '382');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy làm bánh Waffle & Crepe', '441');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy luộc Trứng', '441');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy làm bánh mì', '441');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy làm bánh Takoyaki', '441');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy làm món tráng miệng', '441');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy làm soda', '441');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '441');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ổ cắm điện & Dây nối', '383');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thiết bị an toàn điện tử', '383');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Chuông cửa', '383');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Công tắc', '383');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thiết bị Boá động nhà ở', '383');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thiết bị chống sét', '383');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '383');
INSERT INTO `shopee`.`category` (`name_category`) VALUES ('Giày Dép Nam');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bốt', '460');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Giày thể thao / Sneakers', '460');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Giày sục', '460');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Giày tây lười', '460');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Giày Oxfords & Giày buộc dây', '460');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Xăng-đan & Dép', '460');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Phụ kiện giày dép', '460');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '460');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bốt thời trăng', '461');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bốt đi mưa', '461');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bốt bảo hộ', '461');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '461');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dép xỏ ngón', '466');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Xăng - đan', '466');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dép đi trong nhà', '466');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dép mát - xa', '466');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '466');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dụng cụ chăm sóc & Vệ sinh giày', '467');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khử mùi giày dép', '467');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dây giày', '467');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('cây đòn gót & Giữ form giày', '467');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Lót giày', '467');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '467');
INSERT INTO `shopee`.`category` (`name_category`) VALUES ('Điện Thoại & Phụ Kiện');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thẻ sim', '484');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy tính bảng', '484');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Điện thoại', '484');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thiết bị đeo thông minh', '484');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Phụ kiện', '484');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bộ đàm', '484');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '484');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồng hồ thông minh & Vòng đeo tay sức khỏe', '488');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thiết bị thực tế ảo', '488');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thiết bị định vị GPS', '488');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '488');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Phụ kiện selfie', '489');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ống kính điện thoại', '489');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đèn flash điện thoại & Đèn selfie', '489');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Quạt USB & Quạt điện thoại', '489');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bút cảm ứng', '489');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Kẹp điện thoại', '489');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dây đeo điện thoại & Móc khóa', '489');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thẻ nhớ', '489');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thiết bị trình chiếu', '489');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Túi đựng điện thoại', '489');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Cáp, sạc & bộ chuyển đổi', '489');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đèn USB & Đèn điện thoại', '489');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bộ phát Wifi bỏ túi', '489');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Sạc dự phòng & Pin', '489');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Phụ kiện cho đồng hồ thông minh', '489');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Miếng dán màn hình', '489');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Vỏ bao, Ốp lưng & Miếng dán', '489');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '489');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Gậy selfie', '496');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Giá đỡ', '496');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Điều khiển chụp hình', '496');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '496');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bao đựng cáp, Bảo vệ cáp & Cuộn dây', '506');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bộ sạc du lịch', '506');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Cáp & Bộ chuyển đổi di động', '506');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bộ sạc', '506');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đế sạc đứng', '506');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '506');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Pin', '509');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Sạc dự phòng', '509');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Vỏ sạc dự phòng', '509');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '509');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Vỏ bao, Ốp lưng & Miếng dán máy tính bảng', '512');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Vỏ bao, Ốp lưng & Miếng dán điện thoại', '512');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '512');
INSERT INTO `shopee`.`category` (`name_category`) VALUES ('Du lịch & Hành lý');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Vali', '531');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Túi du lịch', '531');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Phụ kiện du lịch', '531');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '531');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Túi trống', '533');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Túi gấp gọn', '533');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Túi dây rút', '533');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Túi khác', '533');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ví hộ chiếu', '534');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Túi du lịch nhiều ngăn', '534');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Áo trùm vali', '534');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thẻ hành lý', '534');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dây đai vali', '534');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khoá vali', '534');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Cân hành lý', '534');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Gối & Bịt mắt', '534');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bộ chiết mỹ phẩm', '534');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Phụ kiện khác', '534');
INSERT INTO `shopee`.`category` (`name_category`) VALUES ('Túi Ví Nữ');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ba lô', '550');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Cặp laptop', '550');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ví dự tiệc & Ví cầm tay', '550');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Túi đeo hông & Túi đeo ngực', '550');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Túi tote', '550');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Túi quai xách', '550');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Túi đeo chéo & Túi đeo vai', '550');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ví', '550');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Phụ kiện túi', '550');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '550');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Túi & cặp đứng laptop', '552');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Túi chống sốc laptop', '552');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ba lô laptop', '552');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '552');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ví đựng thẻ', '558');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ví mini đựng tiền', '558');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ví đựng điện thoại & chìa khoá', '558');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ví gập', '558');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ví dài', '558');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ví khác', '558');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dây đeo túi', '559');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dụng cụ treo / đựng túi', '559');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Charm và phụ kiên gắn túi', '559');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Túi da ngăn tiện ích', '559');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dụng cụ vệ sinh và chăm sóc túi', '559');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Phụ kiện khác', '559');
INSERT INTO `shopee`.`category` (`name_category`) VALUES ('Giày Dép Nữ');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bốt', '577');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Giày thể thao / sneaker', '577');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Giày đế bằng', '577');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Giày cao gót', '577');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Giày đế xuồng', '577');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Xăng - đan và dép', '577');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Phụ kiện & chăm sóc giày', '577');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '577');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bốt đi mưa', '578');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bốt thời trang', '578');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '578');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Giày Bale', '580');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Giày lười', '580');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Giày Oxford & Giày buộc dây', '580');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Giày sục & Giày búp bê', '580');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '580');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Xăng - đan đế bằng', '583');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dép kẹp / dép xỏ ngón', '583');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dép mát - xa', '583');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dép đi trong nhà', '583');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '583');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ khử mùi giày', '584');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Miéng lót giày', '584');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Cây đón gót & làm sạch giày', '584');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dây giày', '584');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '584');
INSERT INTO `shopee`.`category` (`name_category`) VALUES ('Túi Ví Nam');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ba lô', '604');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Cặp laptop', '604');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Túi tote', '604');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Cặp xách công sở', '604');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ví cầm tay', '604');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Túi đeo hông & Túi đeo ngực', '604');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Túi đeo chéo', '604');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bóp / ví', '604');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '604');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Túi & cặp đựng laptop', '606');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Túi chống sốc laptop', '606');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ba lô laptop', '606');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '606');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ví đựng thẻ', '612');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ví đựng tiền xu', '612');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ví đựng điện thoại & chìa khoá', '612');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ví gập đôi & gập ba', '612');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ví dài', '612');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ví khác', '612');
INSERT INTO `shopee`.`category` (`name_category`) VALUES ('Đồng Hồ');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồng hồ nữ', '624');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồng hồ nam', '624');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bộ đồng hồ & Đồng hò cặp', '624');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Phụ kiện đồng hồ', '624');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '624');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dây đồng hồ', '628');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dụng cụ sữa chữa', '628');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khoá đồng hồ', '628');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Pin đồng hồ', '628');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Hộp đựng đồng hồ', '628');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '628');
INSERT INTO `shopee`.`category` (`name_category`) VALUES ('Thiết Bị Âm Thanh');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Tai nghe nhét tai & chụp tai', '636');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy nghe nhạc', '636');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Micro thu âm', '636');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Amply và đầu chỉnh âm', '636');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Dàn âm thanh', '636');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Cáp âm thanh/ video & Đầu chuyển', '636');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '636');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('MP3 & MP4', '638');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('CD, DVD & Bluray', '638');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Máy ghi âm', '638');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Radio & Cát-sét', '638');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '638');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Loa', '641');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Hệ thống âm thanh giải trí tại gia', '641');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thu sóng AV', '641');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '641');
INSERT INTO `shopee`.`category` (`name_category`) VALUES ('Thực phẩm và đồ uống');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ chế biến sẵn', '653');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ ăn vặt', '653');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Nhu yếu phẩm', '653');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Nguyên liệu nấu ăn', '653');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ làm bánh', '653');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Ngũ cốc & mứt', '653');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ uống', '653');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Sữa - trứng', '653');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thực phẩm tưới sống & động lạnh', '653');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Các loại banh', '653');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ uống có cồn', '653');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bộ quà tặng', '653');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '653');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đồ ăn chế biến sẵn', '654');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('khác', '654');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Cơm và cháo ăn liền', '654');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Lẩu ăn liền', '654');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Mì ăn liền', '654');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Kẹo', '655');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Sô cô la', '655');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bánh quy', '655');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khoai tây lát', '655');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Các loại hạt sấy khô', '655');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Bỏng ngô', '655');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Các loại rong biển ăn liền', '655');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Các loại đậu sấy khô', '655');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '655');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Pudding, thạch & kẹo dẻo', '655');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thức ăn khô', '655');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thịt khô', '682');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Hoa quả sấy khô', '682');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('chà bông', '682');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Hải sản sấy khô', '682');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '682');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thực phẩm khô', '656');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Mì', '656');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Gạo', '656');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Mì Ý', '656');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '656');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thực phẩm đóng hộp', '656');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Rau củ ngâm', '656');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Đậu & ngũ cốc', '688');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Hải sản sấy khô', '688');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thảo mộc truyền thống', '688');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '688');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Trái cây đóng hộp', '693');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Thịt hộp', '693');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Hải sản đóng hộp', '693');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Rau củ đóng hộp', '693');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Súp hộp', '693');
INSERT INTO `shopee`.`category` (`name_category`, `id_parent`) VALUES ('Khác', '693');
-- Thực phẩm và đồ uống > Nguyên liệu nấu ăn
