// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using test_Dbcontext_asp.Data;

#nullable disable

namespace test_Dbcontext_asp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250422022033_addBook")]
    partial class addBook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("test_Dbcontext_asp.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rate")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "First Author",
                            DateAdded = new DateTime(2025, 4, 22, 9, 20, 33, 201, DateTimeKind.Local).AddTicks(4010),
                            Description = "1st book description",
                            Genre = "Biography",
                            Rate = 5,
                            Title = "1st book title"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Second Author",
                            DateAdded = new DateTime(2025, 4, 22, 9, 20, 33, 202, DateTimeKind.Local).AddTicks(6721),
                            Description = "2nd book description",
                            Genre = "Biography",
                            Rate = 4,
                            Title = "2nd book title"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
