// <auto-generated />
using System;
using BusinessObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessObjects.Migrations
{
    [DbContext(typeof(FunewsManagementContext))]
    [Migration("20250306152527_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObjects.Category", b =>
                {
                    b.Property<short>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("CategoryId"));

                    b.Property<string>("CategoryDesciption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<short?>("ParentCategoryId")
                        .HasColumnType("smallint");

                    b.HasKey("CategoryId")
                        .HasName("PK__Category__19093A0BAF714996");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.NewsArticle", b =>
                {
                    b.Property<Guid>("NewsArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<short?>("CategoryId")
                        .HasColumnType("smallint");

                    b.Property<short?>("CreatedById")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("NewsContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewsSource")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("NewsStatus")
                        .HasColumnType("bit");

                    b.Property<string>("NewsTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<short?>("UpdatedById")
                        .HasColumnType("smallint");

                    b.HasKey("NewsArticleId")
                        .HasName("PK__NewsArti__4CD0928C225EFD29");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("NewsArticle", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.SystemAccount", b =>
                {
                    b.Property<short>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("AccountId"));

                    b.Property<string>("AccountEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AccountPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountRole")
                        .HasColumnType("int");

                    b.HasKey("AccountId")
                        .HasName("PK__SystemAc__349DA5A6C8C0B284");

                    b.HasIndex(new[] { "AccountEmail" }, "UQ__SystemAc__FC770D330E290670")
                        .IsUnique();

                    b.ToTable("SystemAccount", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TagId")
                        .HasName("PK__Tag__657CF9AC39B9820B");

                    b.ToTable("Tag", (string)null);
                });

            modelBuilder.Entity("NewsArticleTag", b =>
                {
                    b.Property<Guid>("NewsArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("NewsArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("NewsArticleTag", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.Category", b =>
                {
                    b.HasOne("BusinessObjects.Category", "ParentCategory")
                        .WithMany("InverseParentCategory")
                        .HasForeignKey("ParentCategoryId")
                        .HasConstraintName("FK_Category_Parent");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("BusinessObjects.NewsArticle", b =>
                {
                    b.HasOne("BusinessObjects.Category", "Category")
                        .WithMany("NewsArticles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_NewsArticle_Category");

                    b.HasOne("BusinessObjects.SystemAccount", "CreatedBy")
                        .WithMany("NewsArticleCreatedBies")
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("FK_NewsArticle_CreatedBy");

                    b.HasOne("BusinessObjects.SystemAccount", "UpdatedBy")
                        .WithMany("NewsArticleUpdatedBies")
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("FK_NewsArticle_UpdatedBy");

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("NewsArticleTag", b =>
                {
                    b.HasOne("BusinessObjects.NewsArticle", null)
                        .WithMany()
                        .HasForeignKey("NewsArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NewsArticleTag_NewsArticle");

                    b.HasOne("BusinessObjects.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NewsArticleTag_Tag");
                });

            modelBuilder.Entity("BusinessObjects.Category", b =>
                {
                    b.Navigation("InverseParentCategory");

                    b.Navigation("NewsArticles");
                });

            modelBuilder.Entity("BusinessObjects.SystemAccount", b =>
                {
                    b.Navigation("NewsArticleCreatedBies");

                    b.Navigation("NewsArticleUpdatedBies");
                });
#pragma warning restore 612, 618
        }
    }
}
